packages:
- '.'
extra-deps:
- filestore-0.6.3.1
- pandoc-2.0
- pandoc-types-1.17.2
- hslua-0.9.2
- skylighting-0.4.2
- cmark-gfm-0.1.1
- QuickCheck-2.10.0.1
- tasty-quickcheck-0.9.1
- doctemplates-0.2.1
- haddock-library-1.4.3
- git: https://github.com/thoughtbot/yesod-auth-oauth2.git
  commit: b1181298ba4fc25dcb3a5e6b11f1188986f131a4
- git: git@github.com:phadej/github.git
  commit: e4bab2ef4d2d10030a0c37c963fc8882fabad847

resolver: lts-9.9
